version: "3.8"
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - HOST: "GenesisTestTask_default",
      - PORT: 3306,
      - USERNAME: "node",
      - PASSWORD: "pass",
      - DATABASE: "Weather",
  db:
    build: ./mysql
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
